# Generated by Django 4.2 on 2023-06-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_department_dep_description_department_dep_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dep_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='department',
            name='dep_name',
            field=models.CharField(max_length=20),
        ),
    ]
